### GENERAL SETTINGS ###

# Site settings
title: MND Malaysia
description: "MND Malaysia supports people living with Motor Neurone Disease across Malaysia"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
#url: "http://www.mnd.org.my"
url: "https://aizawa82.github.io/mndsource"
# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
#  primary: "#00b3fe" #"#F70031" 
  primary: "#9bc7ee" #"#F70031" 4982cf
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
# secondary: "#384452" #"#33004D"
  secondary: "#4982cf"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d5"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/MND-Malaysia-688240477971342/
  - title: twitter
    url: https://twitter.com/mnd_malaysia
  - title: youtube
    url: https://www.youtube.com/channel/UCp09uYWx_gdIdDY5TdRd_-w


    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Pusat Perubatan Universiti Malaya
    - 59100 Kuala Lumpur
    - Wilayah Persekutuan	
email: contact@mnd.org.my
tel: +6017-8838839


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:

  - name: Benny Ng
    img: benny.jpeg
    position: Chairman
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Cheong Soo Futt
    img: soo.jpeg
    position: Volunteer
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Joe Liew
    img: joe.jpeg
    position: Volunteer
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Magdeline Liew
    img: magdeline.jpeg
    position: Volunteer
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: ET Ong
    img: et.jpeg
    position: Volunteer
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Prof. Dr. Goh Khean Jin
    img: goh.jpeg
    position: Consultant Neurologist
    text: Consultant in the department of neurology at University Malaya Medical Centre.
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Dr. Loh Ee Chin
    img: loh.jpeg
    position: Consultant Palliative Care Physician
    text: Consultant in the department of neurology at University Malaya Medical Centre.
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name:  Prof. Dr. Lydia Binti Abdul Latif
    img: lydia.jpeg
    position: Consultant Rehabilitative Physician
    text: Consultant in the department of rehabilitation medicine at University Malaya Medical Centre.
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name:   Prof. Dr. Nortina Shahrizaila 
    img: nortina.jpeg
    position: Consultant Neurologist
    text: Consultant in the department of neurology at University Malaya Medical Centre.
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name:  Dr. Sheriza Izwa Zainuddin
    img: sheriza.jpeg
    position: Consultant Palliative Care Physician
    text: Consultant in the department of palliative care at University Malaya Medical Centre.
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Dr. David Capelle 
    img: david.jpeg
    position: Volunteer
    text: Registrar at University Malaya Medical Centre. 
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

  - name: Dr. Ng Woon Fang
    img: wf.jpeg
    position: Volunteer
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle


    
# Clients information. Shown on Home and About pages.

    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "MND Malaysia supports people living with Motor Neurone Disease across Malaysia"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
